package org.example.userhandleapi.DTO;

public enum AuthStatus {
    USER_CREATED_SUCCESSFULLY, USER_NOT_CREATED, LOGIN_SUCCESS, LOGIN_FAILED, SUCCESS,UNSUCCESSFUL, DOCTOR_ADDED_SUCCESSFULLY,
    HOSPITAL_NOT_PRESENT, SOMETHING_WENT_WRONG, EMAIL_ALREADY_EXISTS, PHONE_NUMBER_ALREADY_EXISTS

}
